GET http://localhost:3000/api/persons/

###

GET http://localhost:3000/api/persons/65200c29d75327cdfa6f7544


###

POST http://localhost:3000/api/persons/
Content-Type: application/json

{
    "name": "frank ramos",
    "education": "college",
    "gender": "Male",
    "experience": "sample experience",
    "about_me": "sample about me"
}

###
PATCH http://localhost:3000/api/persons/65200c29d75327cdfa6f7544
Content-Type: application/json

{
    "name": "Frank sample"
}

###
DELETE  http://localhost:3000/api/persons/65200c29d75327cdfa6f7544